### ISSUE TITLE
Add ability to turn a project into a package

### ISSUE THREAD

**Issue by rapus95** [invenia/PkgTemplates.jl#136] opened 2020-02-11 10:59 UTC
Currently you can only create packages when there hasn't been a project before. It'd be nice to convert an already existing project into a package. I'd envision the function name "package" (optionally with an exclamation mark! at the end).
In combination with #135 you'd then be able to simply call pkg"package" in the repl mode to turn a project into a package which would be very convenient and simple to follow.

**Comment by christopher-dG** [comment] 2020-02-11 12:22
This is a dupe of #16, I believe

**Closed by christopher-dG** 2020-02-11 12:22 UTC

**Comment by rapus95** [comment] 2020-02-11 12:42
Just a little less cryptic as it seems. it also highlights the differences between packages and projects.
In fact, the workflow parseproject() -> changeprojectobj() -> saveprojectobj() is the primary thing which is needed to unify #136 and #16

**Comment by christopher-dG** [comment] 2020-02-11 12:43
I'm honestly not sure what is meant by "project" here. Could you enlighten me?

**Comment by rapus95** [comment] 2020-02-11 13:00
All the subtle differences layouted there: https://julialang.github.io/Pkg.jl/v1/glossary/

**Comment by christopher-dG** [comment] 2020-02-11 13:06
Ok yeah, Lyndon's very recent comment actually addresses this exact situation, if I'm reading it correctly. .
