### ISSUE TITLE
Add to an older package?

### ISSUE THREAD

**Issue by timholy** [invenia/PkgTemplates.jl#234] opened 2020-09-21 10:21 UTC
I have an old "package," https://github.com/timholy/DebuggingUtilities.jl, and it would be nice to add GitHubActions support to it using PkgTemplates. For example:

```julia
using PkgTemplates
t = Template(plugins=[GitHubActions()])
t("DebuggingUtilities"; extend=true)
```

Currently I do that by creating a junk package and then manually copying configuration files, then deleting the junk package.

**Comment by christopher-dG** [comment] 2020-09-21 15:51
Dupe of #16, this has been long desired 😅

**Closed by christopher-dG** 2020-09-21 15:51 UTC

**Comment by timholy** [comment] 2020-09-22 10:29
Ah, thanks, sorry for the duplicate!
